### ISSUE TITLE
can' run

### ISSUE THREAD

**Issue by GUANCAIBAN** [Ghost53574/havoc_profile_generator#1]

**Comment by GUANCAIBAN** [comment]
maybe after update the code,you don't run the script again, so many bug here,run command such as 
`python3 ./havoc_profile_generator.py  -c ./chrome.json -q > ./havoc_chrome.yaotl ` ,it can't run, I try to fix it,but another bug has appeared

**Comment by Ghost53574** [comment]
The thing is, it's Python. It's an unfinished tool and between my job and my family life I don't really have all the time in the world to dedicate to active development of just one tool that was created because a user on C5piders discord cried about not having a profile generator I made something janky in about five hours.

What would help you and everyone else is a little bit of effort from you to describe what the "bugs" are, what the output is, and maybe even a PR or two.

Thanks

**Comment by Ghost53574** [comment]
So instead of helping diagnose the issues you decided to do the good old complain then give up. It's python, it's a scripting language. It took me all of ten minutes to find all of the issues thus far that were just issues that were due to the changes to the code base that are literally easily solved because each exception gives a line number with the issue.

If you were more helpful in solving the problems instead of just whining that problems existed maybe you would have been more of a help to the community in general.
